### ISSUE TITLE
建议将wepy-cropper.scss改为less

### ISSUE THREAD

**Issue by Licoy** [callmesoul/wepy-corpper#10]
看了一下wepy-cropper.scss的文件内容，并没有用到scss的任何特性，在客户端时候的时候build其scss文件并没有输出到dist下，所以建议作者将scss改为less或者wxss。

**Comment by callmesoul** [comment]
less和scss 其实都用一样，因为平时开发都用scss所以就用了scss。
打包时没有输出到dist，可以检查下是否配置好scss。
或wepy版本是否1.7.2。 该版本有bug升级下就好
@Licoy

**Comment by Licoy** [comment]
@callmesoul ok
