### ISSUE TITLE
template最外层的scroll-view应改为view

### ISSUE THREAD

**Issue by MaxMooc** [callmesoul/wepy-corpper#2]
关于template最外层的scroll-view应改为view, 因为scroll-view  设置width 100%，不生效

**Comment by callmesoul** [comment]
@MaxMooc 测试过没问题的，不过也好像却是用不到scroll-view。但有没有其他用意，要再看看

**Comment by callmesoul** [comment]
@MaxMooc 用scroll-view是为了防止iPhone页面弹簧效果

**Comment by MaxMooc** [comment]
@callmesoul   嗯 ,好的，scroll-view  在开发工具（v1.02.1802270）上弹层显示出不来，真机正常，感谢回答

**Comment by callmesoul** [comment]
客气，大家互相交流学习
