### ISSUE TITLE
Bug：首次打开图片的时候，右上角和左上角的两个角无法拖动

### ISSUE THREAD

**Issue by jimmyrogue** [callmesoul/wepy-corpper#5]
如题，首次使用时，上方的两个角都无法拖动
但是只要下发对应的角拖动一下就可以正常拖动了

**Comment by tomfriwel** [comment]
@callmesoul 不确定，因为我代码最近更新过，所以可能`wepy`版存在之前的问题。
以前的确有这样的问题。

**Comment by jimmyrogue** [comment]
@tomfriwel wepy版是每次都会出现。但只要打开过一次 第二次打开似乎就没有问题了

**Comment by tomfriwel** [comment]
@jimmyrogue 你可以试试原生的，因为这个`wepy`版并不是我维护的。
如果原生的没问题，你可以自己试着替换掉`wepy`版本的核心代码，核心代码都一样。

**Comment by jimmyrogue** [comment]
@tomfriwel 好的

**Comment by walkedSnail** [comment]
我这边也出现这个问题了，然后更换小程序基础库为2.1.0以上就不会有问题了

**Comment by callmesoul** [comment]
那应该是小程序的canvas组件问题，大家升级下基础库就好了。
