### ISSUE TITLE
wepy 版本1.7.0及以上编译后无法正常使用

### ISSUE THREAD

**Issue by jimmyrogue** [callmesoul/wepy-corpper#6]
wepy 版本1.7.0及以上编译后无法正常使用
使用命令 npm run build  开启压缩
wepy版本1.7.1

**Comment by callmesoul** [comment]
报什么错了？插件用了scss不知道是否有开启scss和sass，是否安装scss和sass

**Comment by jimmyrogue** [comment]
@callmesoul 没有报错。。。就顺利的编译下来 但是打开就发现图片在页面的上半部分，截图框则在下半部分。

**Comment by callmesoul** [comment]
请检查打包后的css是否正常，我用的1.7.0没问题的。注意开启scss

**Comment by callmesoul** [comment]
用的是1.7.2版本？测试了下，1.7.2版本有bug。scss打包有只有文件，里面的样式是空的。请转回1.7.0版本即可

**Comment by jimmyrogue** [comment]
@callmesoul 好的
